### ISSUE TITLE
BASEURL

### ISSUE THREAD

**Issue by idati** [fboerman/jao-py#4]
Hi,

looks like the Baseurl didnt work?

BASEURL = "https://www.jao.eu/api/v1"

![image](https://user-images.githubusercontent.com/11889312/144045532-0f4d7003-3583-4f37-ba14-cd3df3d34bd4.png)

Thanks :-)

**Comment by fboerman** [comment]
Hi,

I think it only works when you call specific endpoints.

Sent from ProtonMail mobile

-------- Original Message --------
