### ISSUE TITLE
Deprecation Warning due to missing pyproject.toml

### ISSUE THREAD

**Issue by maurerle** [fboerman/jao-py#9]
Currently, installing jao-py with latest pip from source gives this warning:

```
DEPRECATION: jao-py is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed.
pip 23.1 will enforce this behaviour change.
A possible replacement is to enable the '--use-pep517' option.
Discussion can be found at https://github.com/pypa/pip/issues/8559
```

As also mentioned in this PR: https://github.com/EnergieID/entsoe-py/pull/314 I would prefer to switch the build config in this regard to pyproject.toml

**Comment by maurerle** [comment]
The warning has been removed in pip and the installation falls back to run in an isolated build env with wheel installed.

**Comment by fboerman** [comment]
thanks for letting me know!
